name: Arrival Scraper

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 3 minutes
  workflow_dispatch:  # Allows manual triggering of workflow

jobs:
  run-scraper:
    runs-on: ubuntu-latest  # Use GitHub's hosted runner

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python and install dependencies
        run: |
          python3 -m venv myenv  # Create a virtual environment
          source myenv/bin/activate  # Activate the virtual environment
          python --version  # Check Python version
          pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies

      # Step 3: Run the scraper script inside the virtual environment
      - name: Run scraper script
        run: |
          source myenv/bin/activate  # Activate the virtual environment
          python main_script.py  # Run your Python scraper

      # Step 4: Commit and push changes to the main branch
      - name: Commit and push changes to main
        env:
          GITHUB_TOKEN: ${{ secrets.Fids_Arrival }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git stash  # Stash any unstaged changes
          git pull origin main --rebase  # Pull the latest changes and rebase
          git stash pop || true  # Reapply the stashed changes (ignore error if stash was empty)
          git add scraper/output/index.html  # Add the updated HTML file
          git commit -m "Update arrivals HTML file" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.Fids_Arrival }}@github.com/${{ github.repository }} HEAD:main
