name: Arrival Scraper

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of workflow

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 3: Run the scraper script
      - name: Run scraper script
        run: |
          python main_script.py  # Run main_script.py for arrivals

      # Step 4: Move the generated index.html to GitHub Actions workspace for SCP to VM
      - name: Prepare HTML file for SCP
        run: |
          mv scraper/output/index.html ./index.html

      # Step 5: SCP the HTML file to the VM
      - name: SCP HTML file to VM
        run: |
          scp -o StrictHostKeyChecking=no index.html georg_sigurdsson1994@your-vm-ip:/var/www/html/arrivals/index.html
