name: Arrival Scraper

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual triggering of workflow

jobs:
  run-scraper:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python with a specific version
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Specify a valid version like 3.8, 3.9, or 3.10

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Step 4: Run the Python scraper script
      - name: Run scraper script
        run: |
          python main_script.py  # Ensure this is the correct script path

      # Step 5: Commit and push changes to main branch
      - name: Commit and push changes to main
        env:
          GITHUB_TOKEN: ${{ secrets.Fids_Arrival }}  # Use your secret token here
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add scraper/output/index.html  # Ensure this path is correct for your generated HTML
          git commit -m "Update arrivals HTML file"
          git push https://x-access-token:${{ secrets.Fids_Arrival }}@github.com/${{ github.repository }} HEAD:main
