name: Arrival Scraper

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual triggering of workflow

jobs:
  run-scraper:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Check Python version (Optional)
      - name: Check Python version
        run: python --version  # Check the default Python version

      # Step 3: Run the scraper script (if it's in Python)
      - name: Run scraper script
        run: |
          python main_script.py  # Use the system's default Python if installed

      # Step 4: Commit and push changes
      - name: Commit and push changes to main
        env:
          GITHUB_TOKEN: ${{ secrets.Fids_Arrival }}  # Use your secret token here
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add scraper/output/index.html  # Ensure this path is correct for your generated HTML
          git commit -m "Update arrivals HTML file"
          git push https://x-access-token:${{ secrets.Fids_Arrival }}@github.com/${{ github.repository }} HEAD:main
