name: Arrival Scraper

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of workflow

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with the desired version

      # Step 3: Install dependencies (Optional)
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt || echo "No requirements file found"

      # Step 4: Run the scraper script from root directory
      - name: Run scraper script
        run: |
          python main_script.py

      # Step 5: Commit and push the updated index.html file to the repository
      - name: Commit and push changes to main
        env:
          GITHUB_TOKEN: ${{ secrets.Fids_Arrival }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add scraper/output/index.html
          git commit -m "Update arrivals HTML file" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.Fids_Arrival }}@github.com/${{ github.repository }} HEAD:main
